# Generated by Django 6.0.5 on 2026-05-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_branch_unique_branch_team_unique_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='employees.team'),
            preserve_default=False,
        ),
    ]
