# Generated by Django 6.0.5 on 2026-05-24 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationrun",
            old_name="n_recipient",
            new_name="n_recipients",
        ),
        migrations.RemoveField(
            model_name="notificationrun",
            name="notification_date",
        ),
    ]
